name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install other dependencies
      run: |
        pip install ".[mxnet,arrow,shell]" \
          -r requirements/requirements-test.txt \
          -r requirements/requirements-extras-m-competitions.txt
    - name: Test with pytest
      run: |
        pytest -n2 --doctest-modules --ignore test/nursery test
